import { DASHBOARD_TOUR, INFO_BOX_TOUR } from "./dashboard";
import {
    EXCHANGE_SETTINGS_TOUR,
    GUEST_SAVE_TOUR,
    MEMBERS_PENDING_TOUR,
    NEW_FEATURE_TOUR,
    PAYMENTS_BULK_TOUR,
    PAYMENTS_PENDING_TOUR,
    REQUEST_TEMPLATES_TOUR,
} from "./page-tours";

export const TOURS = [
    DASHBOARD_TOUR,
    INFO_BOX_TOUR,
    PAYMENTS_BULK_TOUR,
    PAYMENTS_PENDING_TOUR,
    EXCHANGE_SETTINGS_TOUR,
    MEMBERS_PENDING_TOUR,
    GUEST_SAVE_TOUR,
    NEW_FEATURE_TOUR,
    REQUEST_TEMPLATES_TOUR,
];
